api:
  dashboard: true
  insecure: false
  debug: false
metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: ":443"
  traefik-dash:
    address: ":8080"
    http:
      tls: false
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: traefik
certificatesResolvers:
  tlschallenge:
    acme:
      email: reachclarakhan.flattery780@aleeas.com
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        #TODO: change to use socket proxy
