services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    restart: unless-stopped
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy_datadir:/data
      # - ${CONIFG_DIR}/tsdproxy/tsdproxy.yaml:/config/tsdproxy.yaml:ro
      # - ${CONIFG_DIR}/tsdproxy/authKeyFile:/config/authKeyFile:ro
      - ./tsdproxy.yaml:/config/tsdproxy.yaml:ro
      - ./authKeyFile:/config/authKeyFile:ro
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=tsdproxy
    networks:
      - tsd-proxy
volumes:
  tsdproxy_datadir:
    name: tsdproxy_datadir
networks:
  tsd-proxy:
    name: tsd-proxy
    external: true
